Basic:
  TIMEZONE: Asia/Shanghai
  BOT_NAME: "@XXXXXX"
  API_TOKEN: XXXXXXXX
  MASTER_ID: XXXXXXXX

GroupChat:
  # ID和群组名称
  - [XXXXXXXX, "XXXXXXXX"]

Weather:
  # 服务商API。目前只支持OpenWeather
  API_KEY: XXXXXXXX
  # 经纬度
  LAT: XXXXXXXX
  LON: XXXXXXXX

OpenAI:
  OPENAI_API_KEY: sk-XXXXXXXX
