[project]
name = "artemis-bot"
version = "0.1.0"
description = "A simple Telegram Bot for my friends."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot==13.15",
    "pyyaml",
    "requests",
    "beautifulsoup4",
    "flask>=3.1.2",
]
